### ISSUE TITLE
Missing background.js

### ISSUE THREAD

**Issue by kristiankunc** [Klicer/bombparty-helper#1]
A background script `background.js` is missing in the project but is referenced & required in [manifest.json:7](https://github.com/Klicer/bombparty-helper/blob/a96ca9eac19243d8aa4685a809a7d7ac35f4906b/manifest.json#L7)

**Comment by Klicer** [comment]
I fixed the issue in question, but seems like jklm.fun has changed something within the past year which has broken this tool. Updated README.md to reflect that.

[commit](https://github.com/Klicer/bombparty-helper/commit/008214d3a3e072dc1e8a761fd545b383f0ac14e6)
